language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

# Use containers on travis-ci
sudo: false

# Cache installed deps
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
install:
  - git clone 'https://github.com/nicfit/mishmash.git' mishmash
  - cd mishmash
  - python setup.py install
  - cd ..
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
  - pip install .

# command to run tests
script:
  coverage run --source=unsonic setup.py test

after_success:
  coveralls
