version: "2"

services:

    unsonic:
        build:
            context: .
            dockerfile: Dockerfile
        image: unsonic

    postgres:
        image: postgres:9.6-alpine
        container_name: PostgreSql
        environment:
            POSTGRES_DB: music
            POSTGRES_USER: unsonic
            POSTGRES_PASSWORD: FaithSubjectToChange

    unsonic-base: &unsonic-container
        image: unsonic
        volumes:
            - /etc/localtime:/etc/localtimel:ro
            - ${MUSIC_DIR}:/media/music:ro

    unsonic-sqlite:
        <<: *unsonic-container
        container_name: Unsonic-sqlite
        environment:
            MISHMASH_DBURL: sqlite:////unsonic/var/music-dev.db
        ports:
            - 16543:6543

    unsonic-postgres:
        <<: *unsonic-container
        container_name: Unsonic-postgres
        environment:
            POSTGRES_PASSWORD: FaithSubjectToChange
            MISHMASH_DBURL: postgresql://unsonic:FaithSubjectToChange@postgres/music-dev
        links:
            - postgres:postgres
        ports:
            - 26543:6543
        depends_on:
            - postgres
