version: "2"

services:

    unsonic: &unsonic
        build:
            context: .
            dockerfile: Dockerfile
        image: nicfit/unsonic

    unsonic-sqlite:
        image: nicfit/unsonic
        container_name: Unsonic-sqlite
        environment:
            MISHMASH_DBURL: sqlite:////unsonic/var/music.db
        volumes:
            - /etc/localtime:/etc/localtimel:ro
            - ${MUSIC_DIR}:/media/music:ro
        ports:
            - 16543:6543

    postgres:
        image: postgres:9.6-alpine
        container_name: PostgreSql-unsonic
        environment:
            POSTGRES_DB: unsonic
            POSTGRES_USER: unsonic
            POSTGRES_PASSWORD: FaithSubjectToChange

    unsonic-postgres:
        image: nicfit/unsonic
        container_name: Unsonic-postgres
        environment:
            POSTGRES_PASSWORD: FaithSubjectToChange
            MISHMASH_DBURL: postgresql://unsonic:FaithSubjectToChange@postgres/unsonic
        links:
            - postgres:postgres
        volumes:
            - /etc/localtime:/etc/localtimel:ro
            - ${MUSIC_DIR}:/media/music:ro
        ports:
            - 26543:6543
        depends_on:
            - postgres

    unsonic.nicfit.net:
        image: nicfit/unsonic
        container_name: unsonic.nicfit.net
        environment:
            MISHMASH_DBURL: sqlite:////unsonic/var/music.db
        volumes:
            - /etc/localtime:/etc/localtimel:ro
            - ${MUSIC_DIR}:/media/music:ro
        ports:
            - 6543:6543
